version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: movimentocodar
      POSTGRES_PASSWORD: movimentocodar
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./data-postgres/:/var/lib/postgres
